/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      gravity_compensation:
        type: crisp_controllers/CartesianImpedanceController

      cartesian_impedance_controller:
        type: crisp_controllers/CartesianImpedanceController

      # joint_controller:
      #   type: lsy_franka_controllers/JointImpedanceController

      # operational_space_controller:
      #   type: lsy_franka_controllers/OperationalSpaceController

      # frictionless_controller:
      #   type: lsy_franka_controllers/FrictionlessController

  joint_trajectory_controller:
    ros__parameters:
      command_interfaces:
        - effort
      state_interfaces:
        - position
        - velocity
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
      gains:
        fr3_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
        fr3_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
        fr3_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }

  joint_state_broadcaster:
    ros__parameters:
      use_local_topics: False

  gravity_compensation:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      end_effector_frame: fr3_hand_tcp
      base_frame: base

      task:
        k_pos_x: 0.0
        k_pos_y: 0.0
        k_pos_z: 500.0
        k_rot_x: 30.0
        k_rot_y: 30.0
        k_rot_z: 30.0

      nullspace: 
        stiffness: 0.0

      use_friction: true
      use_coriolis_compensation: true
      use_local_jacobian: true
      log_timing: false

  cartesian_impedance_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      end_effector_frame: fr3_hand_tcp
      base_frame: base

      task:
        k_pos_x: 400.0
        k_pos_y: 400.0
        k_pos_z: 400.0
        k_rot_x: 30.0
        k_rot_y: 30.0
        k_rot_z: 30.0

      nullspace: 
        stiffness: 0.0

      use_friction: true
      use_coriolis_compensation: true
      use_local_jacobian: true
      log_timing: false

  # operational_space_controller:
  #   ros__parameters:
  #     joints:
  #       - fr3_joint1
  #       - fr3_joint2
  #       - fr3_joint3
  #       - fr3_joint4
  #       - fr3_joint5
  #       - fr3_joint6
  #       - fr3_joint7
  #
  #     end_effector_frame: fr3_hand_tcp
  #
  #     use_fake_hardware: false
  #     translational_stiffness: 400.0
  #     rotational_stiffness: 30.0
  #     nullspace_stiffness: 0.0
  #     max_delta: [0.05, 0.05, 0.05, 10.0, 10.0, 10.0]
  #     use_friction: true
  #
  # joint_controller:
  #   ros__parameters:
  #     joints:
  #       - fr3_joint1
  #       - fr3_joint2
  #       - fr3_joint3
  #       - fr3_joint4
  #       - fr3_joint5
  #       - fr3_joint6
  #       - fr3_joint7
  #
  #     use_fake_hardware: false
  #     joint_stiffness: 
  #       # - 10.0
  #       # - 10.0
  #       # - 10.0
  #       # - 10.0
  #       # - 10.0
  #       # - 10.0
  #       # - 10.0
  #       - 100.0
  #       - 100.0
  #       - 100.0
  #       - 100.0
  #       - 50.0
  #       - 50.0
  #       - 20.0
  #       # - 600.0
  #       # - 600.0
  #       # - 600.0
  #       # - 600.0
  #       # - 250.0
  #       # - 150.0
  #       # - 50.0
  #
  #     # joint_damping:
  #     #   - 20.0
  #     #   - 20.0
  #     #   - 20.0
  #     #   - 10.0
  #     #   - 10.0
  #     #   - 10.0
  #     #   - 5.0
  #
  #     q_home: [0.0, -0.7853, 0.0, -2.3561, 0.0, 1.5708, 0.7853]
